### ISSUE TITLE
关于在embedding_dic中不存在够个词时候用什么替代

### ISSUE THREAD

**Issue by wx805541464** [Irvinglove/TF_Sentence_Similarity_CNN#1]
s1_vec.append(embedding_dic['<unk>']) 是否要改成 s1_vec.append('<unk>')？

**Comment by Irvinglove** [comment]
你的意思是要把s1_vec.append(embedding_dic['<unk>'])改成s1_vec.append(‘’)吗？词向量中如果没有出现的词用<UNK>类表示，这里肯定也是UNK啊。

**Comment by MaryLiLin** [comment]
glove.6B.50d.txt这个文本中没有UNK，会报KeyError: '<unk>'的错

irvinglove回复：UNK指代的是未知的词向量，在glove的文件中使用\<unk\>来指代。glove官网有好几个版本的下载，应该是版本不同。当时上传源码的时候没有上传glove.6B.50d.txt，因为这个文件太大了。给你一个[网盘分享](http://pan.baidu.com/s/1nv5Lkwx)。再运行源码就能开始训练了。
